language: go

matrix:
  include:
    - language: go
      go: "1.14.x"
      cache:
        directories:
          - vendor
      script: go test -v -mod=vendor ./...
    - language: node_js
      cache:
        directories:
          - ./web/node_modules
      node_js:
        - "13"
      before_install:
        - npm install -g yarn
      script:
        - yarn run build
        - yarn test

env:
  - GO111MODULE=on

install: true
