language: go

matrix:
  include:
    - go: "1.10.x"
      script: go test -v ./...
    - go: "1.11.x"
      script: go test -v -mod=vendor ./...
    - go: "1.12.x"
      script: go test -v -mod=vendor ./...
    - go: "1.13.x"
      script: go test -v -mod=vendor ./...
    - go: "1.14.x"
      script: go test -v -mod=vendor ./...

env:
  - GO111MODULE=on

install: true
